FROM ubuntu:latest

RUN apt-get update &&   \
    apt-get install -y  \
    build-essential     \
    git                 \
    vim                 \
    emacs               \
    nano                \
    tree                \
    strace              \
    ltrace              \
    python3-pip         \
    python3-graphviz

CMD ["/usr/bin/env", "bash"]
